import { StyleSheet } from 'react-native';
import type { LandingColors } from './landingTheme';
import { marketingTypography as type } from '../../theme/marketingTypography';

export function landingStyles(c: LandingColors, wide: boolean, small: boolean) {
  const pad = wide ? 48 : 22;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: c.bg },
    header: { backgroundColor: c.bg, borderBottomWidth: 1, borderColor: c.line, zIndex: 2 },
    headerInner: { width: '100%', maxWidth: 1200, alignSelf: 'center', paddingHorizontal: pad, paddingVertical: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    brandRow: { flexDirection: 'row', alignItems: 'center', gap: 9, flexShrink: 1 },
    logo: { width: 30, height: 34 },
    brand: { fontSize: small ? 23 : 26, color: c.ink, fontWeight: '700', flexShrink: 1 },
    nav: { flex: 1, flexDirection: 'row', justifyContent: 'center', gap: 24 },
    navTouch: { minHeight: 44, justifyContent: 'center' },
    navText: { fontSize: 14, color: c.muted, fontWeight: '500' },
    headerLogin: { flexDirection: 'row', gap: 8, minHeight: 44, alignItems: 'center', flexShrink: 1 },
    hero: { maxWidth: 1200, alignSelf: 'center', width: '100%', paddingHorizontal: pad, paddingTop: wide ? 100 : 48, paddingBottom: wide ? 110 : 64, flexDirection: wide ? 'row' : 'column', alignItems: 'center', gap: wide ? 64 : 44 },
    heroText: { flex: wide ? 1.05 : undefined, width: wide ? undefined : '100%', gap: 24 },
    eyebrowRow: { flexDirection: 'row', gap: 10, alignItems: 'center' },
    mark: { width: 18, height: 3, backgroundColor: c.positive },
    eyebrow: { ...type.eyebrow, color: c.positive, flexShrink: 1 },
    h1: { fontSize: wide ? 64 : 40, lineHeight: wide ? 68 : 44, fontWeight: '600', letterSpacing: wide ? -2.8 : -1.5, color: c.ink },
    lead: { fontSize: 17, lineHeight: 28, color: c.muted, maxWidth: 450 },
    actions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 12, marginTop: 8 },
    primary: { minHeight: 48, paddingHorizontal: 22, paddingVertical: 14, backgroundColor: c.accent, borderRadius: 8, flexDirection: 'row', gap: 14, alignItems: 'center', justifyContent: 'center' },
    primaryText: { ...type.primaryLabel },
    secondary: { minHeight: 48, paddingHorizontal: 12, paddingVertical: 14, justifyContent: 'center' },
    secondaryText: { fontSize: small ? 12 : 14, fontWeight: '600', color: c.ink },
    heroVisual: { flex: wide ? 1 : undefined, width: wide ? undefined : '100%', paddingTop: 24, paddingBottom: 8 },
    visualBackdrop: { position: 'absolute', top: 0, bottom: 44, left: wide ? 36 : 18, right: wide ? -24 : -10, backgroundColor: c.soft, borderRadius: 20 },
    productFrame: { width: '100%', borderRadius: 16, overflow: 'hidden', boxShadow: '0 16px 40px rgba(13, 47, 39, 0.07)' },
    imageFrame: { minHeight: wide ? 420 : 300, overflow: 'hidden', borderRadius: 16, backgroundColor: c.surface },
    visualNote: { flexDirection: 'row', gap: 12, alignItems: 'center', marginTop: 24, paddingLeft: 16 },
    smallLine: { width: 24, height: 1, backgroundColor: c.positive },
    caption: { fontSize: 11, lineHeight: 18, color: c.muted, flexShrink: 1 },
    featureSection: { backgroundColor: c.soft },
    container: { maxWidth: 1200, width: '100%', alignSelf: 'center', paddingHorizontal: pad, paddingVertical: wide ? 88 : 56 },
    sectionHeading: { maxWidth: 670, gap: 16, marginBottom: wide ? 56 : 32 },
    h2: { fontSize: wide ? 44 : 32, lineHeight: wide ? 50 : 38, color: c.ink, fontWeight: '600', letterSpacing: -1.4 },
    body: { ...type.body, color: c.muted },
    featureSpotlight: { flexDirection: wide ? 'row' : 'column-reverse', gap: wide ? 80 : 32, alignItems: 'center' },
    budgetVisual: { width: wide ? '46%' : '100%' },
    featureEditorial: { flex: wide ? 1 : undefined, gap: 32, width: wide ? undefined : '100%' },
    featureLead: { flexDirection: 'row', gap: 20 },
    index: { fontSize: 12, color: c.positive, paddingTop: 7, fontWeight: '600' },
    featureTitle: { fontSize: wide ? 28 : 24, lineHeight: 32, letterSpacing: -0.7, color: c.ink, fontWeight: '600' },
    featureList: { flexDirection: 'row', flexWrap: 'wrap', gap: wide ? 32 : 24, marginTop: wide ? 64 : 40 },
    featureItem: { width: wide ? '21%' : small ? '100%' : '46%', flexGrow: 1, borderTopWidth: 1, borderColor: c.line, paddingTop: 24, gap: 12 },
    smallTitle: { ...type.featureTitle, color: c.ink },
    smallBody: { ...type.smallBody, color: c.muted, flexShrink: 1 },
    commitments: { maxWidth: 1200, width: '100%', alignSelf: 'center', paddingHorizontal: pad, paddingVertical: wide ? 72 : 48, flexDirection: wide ? 'row' : 'column', gap: 36 },
    commitmentTitle: { width: wide ? 240 : undefined, fontSize: 28, lineHeight: 35, color: c.ink, letterSpacing: -0.8, fontWeight: '600' },
    commitmentList: { flex: 1, flexDirection: small ? 'column' : 'row', gap: 24, flexWrap: 'wrap' },
    commitment: { flex: small ? undefined : 1, minWidth: small ? undefined : 120, borderLeftWidth: small ? 0 : 1, borderTopWidth: small ? 1 : 0, borderColor: c.line, paddingLeft: small ? 0 : 24, paddingTop: small ? 16 : 0, flexDirection: small ? 'row' : 'column', alignItems: small ? 'center' : 'flex-start', gap: 12 },
    statValue: { fontSize: 32, lineHeight: 40, fontWeight: '600', letterSpacing: -1, color: c.positive, minWidth: small ? 110 : undefined },
    final: { backgroundColor: c.deep, overflow: 'hidden' },
    finalInner: { maxWidth: 1200, alignSelf: 'center', width: '100%', paddingHorizontal: pad, paddingVertical: wide ? 88 : 56, flexDirection: 'row', alignItems: 'center', gap: 64 },
    finalCopy: { flex: 1, gap: 20, maxWidth: 740 },
    finalTitle: { fontSize: wide ? 52 : 36, lineHeight: wide ? 58 : 42, letterSpacing: -1.7, fontWeight: '500', color: c.white },
    finalBody: { fontSize: 17, lineHeight: 27, maxWidth: 520, color: '#C1D5CB' },
    finalSymbol: { width: 170, gap: 22, alignItems: 'flex-end', transform: [{ rotate: '-35deg' }], opacity: 0.4 },
    symbolLine: { width: 64, height: 16, backgroundColor: '#8EBBA5', borderRadius: 4 },
    footer: { maxWidth: 1200, width: '100%', alignSelf: 'center', paddingHorizontal: pad, paddingTop: 48, paddingBottom: 24 },
    footerTop: { flexDirection: wide ? 'row' : 'column', justifyContent: 'space-between', gap: 24 },
    footerMeta: { gap: 12, justifyContent: 'center' },
    footerLinks: { flexDirection: 'row', flexWrap: 'wrap', gap: 24 },
    copyright: { marginTop: 32, paddingTop: 20, borderTopWidth: 1, borderColor: c.line, fontSize: 11, color: c.muted, lineHeight: 18 },
    edit: { position: 'absolute', bottom: 20, right: 20, width: 48, height: 48, borderRadius: 24, backgroundColor: c.deep, alignItems: 'center', justifyContent: 'center' },
  });
}
